// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/0xpelamar/chatbot/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCommonBehaviour creates a new instance of MockCommonBehaviour. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommonBehaviour[T entity.Entity](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommonBehaviour[T] {
	mock := &MockCommonBehaviour[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommonBehaviour is an autogenerated mock type for the CommonBehaviour type
type MockCommonBehaviour[T entity.Entity] struct {
	mock.Mock
}

type MockCommonBehaviour_Expecter[T entity.Entity] struct {
	mock *mock.Mock
}

func (_m *MockCommonBehaviour[T]) EXPECT() *MockCommonBehaviour_Expecter[T] {
	return &MockCommonBehaviour_Expecter[T]{mock: &_m.Mock}
}

// Get provides a mock function for the type MockCommonBehaviour
func (_mock *MockCommonBehaviour[T]) Get(ctx context.Context, ID entity.ID) (T, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.ID) (T, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.ID) T); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.ID) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommonBehaviour_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCommonBehaviour_Get_Call[T entity.Entity] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - ID entity.ID
func (_e *MockCommonBehaviour_Expecter[T]) Get(ctx any, ID any) *MockCommonBehaviour_Get_Call[T] {
	return &MockCommonBehaviour_Get_Call[T]{Call: _e.mock.On("Get", ctx, ID)}
}

func (_c *MockCommonBehaviour_Get_Call[T]) Run(run func(ctx context.Context, ID entity.ID)) *MockCommonBehaviour_Get_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.ID
		if args[1] != nil {
			arg1 = args[1].(entity.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommonBehaviour_Get_Call[T]) Return(v T, err error) *MockCommonBehaviour_Get_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockCommonBehaviour_Get_Call[T]) RunAndReturn(run func(ctx context.Context, ID entity.ID) (T, error)) *MockCommonBehaviour_Get_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Mget provides a mock function for the type MockCommonBehaviour
func (_mock *MockCommonBehaviour[T]) Mget(ctx context.Context, IDs ...entity.ID) ([]T, error) {
	var tmpRet mock.Arguments
	if len(IDs) > 0 {
		tmpRet = _mock.Called(ctx, IDs)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Mget")
	}

	var r0 []T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...entity.ID) ([]T, error)); ok {
		return returnFunc(ctx, IDs...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...entity.ID) []T); ok {
		r0 = returnFunc(ctx, IDs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...entity.ID) error); ok {
		r1 = returnFunc(ctx, IDs...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommonBehaviour_Mget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mget'
type MockCommonBehaviour_Mget_Call[T entity.Entity] struct {
	*mock.Call
}

// Mget is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs ...entity.ID
func (_e *MockCommonBehaviour_Expecter[T]) Mget(ctx any, IDs ...any) *MockCommonBehaviour_Mget_Call[T] {
	return &MockCommonBehaviour_Mget_Call[T]{Call: _e.mock.On("Mget",
		append([]any{ctx}, IDs...)...)}
}

func (_c *MockCommonBehaviour_Mget_Call[T]) Run(run func(ctx context.Context, IDs ...entity.ID)) *MockCommonBehaviour_Mget_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []entity.ID
		var variadicArgs []entity.ID
		if len(args) > 1 {
			variadicArgs = args[1].([]entity.ID)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockCommonBehaviour_Mget_Call[T]) Return(vs []T, err error) *MockCommonBehaviour_Mget_Call[T] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockCommonBehaviour_Mget_Call[T]) RunAndReturn(run func(ctx context.Context, IDs ...entity.ID) ([]T, error)) *MockCommonBehaviour_Mget_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockCommonBehaviour
func (_mock *MockCommonBehaviour[T]) Save(ctx context.Context, ent T) error {
	ret := _mock.Called(ctx, ent)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, T) error); ok {
		r0 = returnFunc(ctx, ent)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommonBehaviour_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockCommonBehaviour_Save_Call[T entity.Entity] struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - ent T
func (_e *MockCommonBehaviour_Expecter[T]) Save(ctx any, ent any) *MockCommonBehaviour_Save_Call[T] {
	return &MockCommonBehaviour_Save_Call[T]{Call: _e.mock.On("Save", ctx, ent)}
}

func (_c *MockCommonBehaviour_Save_Call[T]) Run(run func(ctx context.Context, ent T)) *MockCommonBehaviour_Save_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 T
		if args[1] != nil {
			arg1 = args[1].(T)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommonBehaviour_Save_Call[T]) Return(err error) *MockCommonBehaviour_Save_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommonBehaviour_Save_Call[T]) RunAndReturn(run func(ctx context.Context, ent T) error) *MockCommonBehaviour_Save_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockAccount creates a new instance of MockAccount. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccount(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccount {
	mock := &MockAccount{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccount is an autogenerated mock type for the Account type
type MockAccount struct {
	mock.Mock
}

type MockAccount_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccount) EXPECT() *MockAccount_Expecter {
	return &MockAccount_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockAccount
func (_mock *MockAccount) Get(ctx context.Context, ID entity.ID) (entity.Account, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.ID) (entity.Account, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.ID) entity.Account); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		r0 = ret.Get(0).(entity.Account)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.ID) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccount_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAccount_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - ID entity.ID
func (_e *MockAccount_Expecter) Get(ctx any, ID any) *MockAccount_Get_Call {
	return &MockAccount_Get_Call{Call: _e.mock.On("Get", ctx, ID)}
}

func (_c *MockAccount_Get_Call) Run(run func(ctx context.Context, ID entity.ID)) *MockAccount_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.ID
		if args[1] != nil {
			arg1 = args[1].(entity.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccount_Get_Call) Return(account entity.Account, err error) *MockAccount_Get_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockAccount_Get_Call) RunAndReturn(run func(ctx context.Context, ID entity.ID) (entity.Account, error)) *MockAccount_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Mget provides a mock function for the type MockAccount
func (_mock *MockAccount) Mget(ctx context.Context, IDs ...entity.ID) ([]entity.Account, error) {
	var tmpRet mock.Arguments
	if len(IDs) > 0 {
		tmpRet = _mock.Called(ctx, IDs)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Mget")
	}

	var r0 []entity.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...entity.ID) ([]entity.Account, error)); ok {
		return returnFunc(ctx, IDs...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...entity.ID) []entity.Account); ok {
		r0 = returnFunc(ctx, IDs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...entity.ID) error); ok {
		r1 = returnFunc(ctx, IDs...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccount_Mget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mget'
type MockAccount_Mget_Call struct {
	*mock.Call
}

// Mget is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs ...entity.ID
func (_e *MockAccount_Expecter) Mget(ctx any, IDs ...any) *MockAccount_Mget_Call {
	return &MockAccount_Mget_Call{Call: _e.mock.On("Mget",
		append([]any{ctx}, IDs...)...)}
}

func (_c *MockAccount_Mget_Call) Run(run func(ctx context.Context, IDs ...entity.ID)) *MockAccount_Mget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []entity.ID
		var variadicArgs []entity.ID
		if len(args) > 1 {
			variadicArgs = args[1].([]entity.ID)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockAccount_Mget_Call) Return(accounts []entity.Account, err error) *MockAccount_Mget_Call {
	_c.Call.Return(accounts, err)
	return _c
}

func (_c *MockAccount_Mget_Call) RunAndReturn(run func(ctx context.Context, IDs ...entity.ID) ([]entity.Account, error)) *MockAccount_Mget_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockAccount
func (_mock *MockAccount) Save(ctx context.Context, ent entity.Account) error {
	ret := _mock.Called(ctx, ent)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Account) error); ok {
		r0 = returnFunc(ctx, ent)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccount_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockAccount_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - ent entity.Account
func (_e *MockAccount_Expecter) Save(ctx any, ent any) *MockAccount_Save_Call {
	return &MockAccount_Save_Call{Call: _e.mock.On("Save", ctx, ent)}
}

func (_c *MockAccount_Save_Call) Run(run func(ctx context.Context, ent entity.Account)) *MockAccount_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Account
		if args[1] != nil {
			arg1 = args[1].(entity.Account)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccount_Save_Call) Return(err error) *MockAccount_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccount_Save_Call) RunAndReturn(run func(ctx context.Context, ent entity.Account) error) *MockAccount_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChat creates a new instance of MockChat. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChat(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChat {
	mock := &MockChat{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChat is an autogenerated mock type for the Chat type
type MockChat struct {
	mock.Mock
}

type MockChat_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChat) EXPECT() *MockChat_Expecter {
	return &MockChat_Expecter{mock: &_m.Mock}
}

// ChatUsers provides a mock function for the type MockChat
func (_mock *MockChat) ChatUsers(ctx context.Context, ID entity.ID) ([]entity.Account, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for ChatUsers")
	}

	var r0 []entity.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.ID) ([]entity.Account, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.ID) []entity.Account); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.ID) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChat_ChatUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChatUsers'
type MockChat_ChatUsers_Call struct {
	*mock.Call
}

// ChatUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - ID entity.ID
func (_e *MockChat_Expecter) ChatUsers(ctx any, ID any) *MockChat_ChatUsers_Call {
	return &MockChat_ChatUsers_Call{Call: _e.mock.On("ChatUsers", ctx, ID)}
}

func (_c *MockChat_ChatUsers_Call) Run(run func(ctx context.Context, ID entity.ID)) *MockChat_ChatUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.ID
		if args[1] != nil {
			arg1 = args[1].(entity.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChat_ChatUsers_Call) Return(accounts []entity.Account, err error) *MockChat_ChatUsers_Call {
	_c.Call.Return(accounts, err)
	return _c
}

func (_c *MockChat_ChatUsers_Call) RunAndReturn(run func(ctx context.Context, ID entity.ID) ([]entity.Account, error)) *MockChat_ChatUsers_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockChat
func (_mock *MockChat) Get(ctx context.Context, ID entity.ID) (entity.Chat, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.Chat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.ID) (entity.Chat, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.ID) entity.Chat); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		r0 = ret.Get(0).(entity.Chat)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.ID) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChat_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockChat_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - ID entity.ID
func (_e *MockChat_Expecter) Get(ctx any, ID any) *MockChat_Get_Call {
	return &MockChat_Get_Call{Call: _e.mock.On("Get", ctx, ID)}
}

func (_c *MockChat_Get_Call) Run(run func(ctx context.Context, ID entity.ID)) *MockChat_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.ID
		if args[1] != nil {
			arg1 = args[1].(entity.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChat_Get_Call) Return(chat entity.Chat, err error) *MockChat_Get_Call {
	_c.Call.Return(chat, err)
	return _c
}

func (_c *MockChat_Get_Call) RunAndReturn(run func(ctx context.Context, ID entity.ID) (entity.Chat, error)) *MockChat_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Mget provides a mock function for the type MockChat
func (_mock *MockChat) Mget(ctx context.Context, IDs ...entity.ID) ([]entity.Chat, error) {
	var tmpRet mock.Arguments
	if len(IDs) > 0 {
		tmpRet = _mock.Called(ctx, IDs)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Mget")
	}

	var r0 []entity.Chat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...entity.ID) ([]entity.Chat, error)); ok {
		return returnFunc(ctx, IDs...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...entity.ID) []entity.Chat); ok {
		r0 = returnFunc(ctx, IDs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Chat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...entity.ID) error); ok {
		r1 = returnFunc(ctx, IDs...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChat_Mget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mget'
type MockChat_Mget_Call struct {
	*mock.Call
}

// Mget is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs ...entity.ID
func (_e *MockChat_Expecter) Mget(ctx any, IDs ...any) *MockChat_Mget_Call {
	return &MockChat_Mget_Call{Call: _e.mock.On("Mget",
		append([]any{ctx}, IDs...)...)}
}

func (_c *MockChat_Mget_Call) Run(run func(ctx context.Context, IDs ...entity.ID)) *MockChat_Mget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []entity.ID
		var variadicArgs []entity.ID
		if len(args) > 1 {
			variadicArgs = args[1].([]entity.ID)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockChat_Mget_Call) Return(chats []entity.Chat, err error) *MockChat_Mget_Call {
	_c.Call.Return(chats, err)
	return _c
}

func (_c *MockChat_Mget_Call) RunAndReturn(run func(ctx context.Context, IDs ...entity.ID) ([]entity.Chat, error)) *MockChat_Mget_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockChat
func (_mock *MockChat) Save(ctx context.Context, ent entity.Chat) error {
	ret := _mock.Called(ctx, ent)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Chat) error); ok {
		r0 = returnFunc(ctx, ent)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChat_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockChat_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - ent entity.Chat
func (_e *MockChat_Expecter) Save(ctx any, ent any) *MockChat_Save_Call {
	return &MockChat_Save_Call{Call: _e.mock.On("Save", ctx, ent)}
}

func (_c *MockChat_Save_Call) Run(run func(ctx context.Context, ent entity.Chat)) *MockChat_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Chat
		if args[1] != nil {
			arg1 = args[1].(entity.Chat)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChat_Save_Call) Return(err error) *MockChat_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChat_Save_Call) RunAndReturn(run func(ctx context.Context, ent entity.Chat) error) *MockChat_Save_Call {
	_c.Call.Return(run)
	return _c
}
